# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0056_studentevaluations_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Criterios',
                'verbose_name_plural': 'Criterios',
            },
        ),
        migrations.CreateModel(
            name='GroupOfCriterias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('criterias', models.ManyToManyField(to='videoclases.Criteria')),
            ],
            options={
                'verbose_name': 'M\xf3delo de evaluaci\xf3n',
                'verbose_name_plural': 'M\xf3delo de evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Scala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Escala de Evaluaci\xf3n',
                'verbose_name_plural': 'Escalas de Evaluaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='ScalaValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Valores de Escala',
                'verbose_name_plural': 'Valores de Escalas',
            },
        ),
        migrations.AddField(
            model_name='scala',
            name='values',
            field=models.ManyToManyField(to='videoclases.ScalaValue'),
        ),
        migrations.AddField(
            model_name='groupofcriterias',
            name='scala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclases.Scala'),
        ),
        migrations.AddField(
            model_name='groupofcriterias',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclases.Teacher'),
        ),
        migrations.AddField(
            model_name='homework',
            name='criterias',
            field=models.ManyToManyField(to='videoclases.GroupOfCriterias'),
        ),
    ]
