# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0057_auto_20170906_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalavalue',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentevaluations',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
