# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0058_auto_20170909_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='scala',
            name='custom_cal',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
