# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0059_scala_custom_cal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scala',
            name='values',
            field=models.ManyToManyField(blank=True, null=True, to='videoclases.ScalaValue'),
        ),
    ]
