# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0061_auto_20170909_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupofcriterias',
            old_name='value',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='criteria',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupofcriterias',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
