# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0062_auto_20170909_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scala',
            name='custom_cal',
        ),
        migrations.AddField(
            model_name='groupofcriterias',
            name='custom_cal',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
