# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0063_auto_20170909_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriasByTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('criterias', models.ManyToManyField(to='videoclases.Criteria')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclases.Teacher')),
            ],
        ),
        migrations.RenameModel(
            old_name='GroupOfCriterias',
            new_name='ModelsOfCriterias',
        ),
        migrations.AlterModelOptions(
            name='modelsofcriterias',
            options={},
        ),
        migrations.RemoveField(
            model_name='homework',
            name='criterias',
        ),
        migrations.AddField(
            model_name='homework',
            name='scala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videoclases.ModelsOfCriterias'),
        ),
        migrations.AlterField(
            model_name='modelsofcriterias',
            name='criterias',
            field=models.ManyToManyField(to='videoclases.CriteriasByTeacher'),
        ),
    ]
