# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('videoclases', '0065_auto_20170920_1253'), ('videoclases', '0066_remove_modelsofcriterias_teacher'), ('videoclases', '0067_auto_20170920_2311'), ('videoclases', '0068_auto_20170924_2316'), ('videoclases', '0069_auto_20170924_2343'), ('videoclases', '0070_auto_20170924_2353')]

    dependencies = [
        ('videoclases', '0064_auto_20170913_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteriasbyteacher',
            options={'verbose_name': 'Criterio de evaluación', 'verbose_name_plural': 'Criterios de evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='modelsofcriterias',
            options={'verbose_name': 'Módelo de evaluación', 'verbose_name_plural': 'Módelo de evaluaciones'},
        ),
        migrations.RemoveField(
            model_name='modelsofcriterias',
            name='custom_cal',
        ),
        migrations.RemoveField(
            model_name='modelsofcriterias',
            name='description',
        ),
        migrations.AlterField(
            model_name='modelsofcriterias',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='modelsofcriterias',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='modelsofcriterias',
            name='criterias',
        ),
        migrations.RemoveField(
            model_name='modelsofcriterias',
            name='scala',
        ),
        migrations.AddField(
            model_name='homework',
            name='criterias',
            field=models.ManyToManyField(blank=True, to='videoclases.CriteriasByTeacher'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='scala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videoclases.Scala'),
        ),
        migrations.DeleteModel(
            name='ModelsOfCriterias',
        ),
        migrations.CreateModel(
            name='CriteriaResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclases.Criteria')),
            ],
            options={
                'verbose_name': 'Respuesta de Criterios',
                'verbose_name_plural': 'Respuestas Criterios',
            },
        ),
        migrations.AddField(
            model_name='studentevaluations',
            name='criterias',
            field=models.ManyToManyField(blank=True, to='videoclases.CriteriaResponse'),
        ),
        migrations.AlterField(
            model_name='studentevaluations',
            name='copyright',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluations',
            name='format',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluations',
            name='originality',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluations',
            name='pedagogical',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluations',
            name='rythm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluations',
            name='theme',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
